sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
language: php
matrix:
  include:
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=integration
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - COMPOSER_PACKAGE_NAME=somethingdigital/invalidate-admin-passwords
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_script:
  - ./.travis/before_script.sh
script:
  - phpcs --standard=magento2/vendor/magento-ecg/coding-standard/EcgM2 --ignore="magento2/vendor/somethingdigital/invalidate-admin-passwords/Test/*" magento2/vendor/somethingdigital/invalidate-admin-passwords
  - phpunit -c magento2/dev/tests/$TEST_SUITE

