sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
language: php
matrix:
  include:
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=integration
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - COMPOSER_PACKAGE_NAME=somethingdigital/invalidate-admin-passwords
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - composer require magento-ecg/coding-standard
  - ./.travis/before_script.sh
script:
  - php phpcs.phar --standard=vendor/magento-ecg/coding-standard/EcgM2 --ignore="vendor/*" --ignore="magento2/*" .
  - phpunit -c magento2/dev/tests/$TEST_SUITE

